### ISSUE TITLE
*.static.jade files in assets directory are not compiled

### ISSUE THREAD

**Issue by cappadona** [bmatcuk/jade-brunch-static#1]
Just copied over as is. Something obvious I'm missing?

Here are my dependencies from `package.json`:

``` json
"devDependencies": {
    "brunch": "^1.8.5",
    "brunch-static": "^1.0.0",
    "html-brunch-static": "^1.1.0",
    "jade-brunch-static": "^1.1.0",
    "javascript-brunch": "^1.8.0",
    "sass-brunch": "^1.9.1",
    "uglify-js-brunch": ">= 1.0 < 1.9"
  }
```

And relevant config from `brunch-config.coffee`:

``` coffee
plugins:
  static:
    processors: [
      require('html-brunch-static') {
        processors: [
          require('jade-brunch-static')(pretty: true)
        ]
      }
    ]
```

**Comment by bmatcuk** [comment]
That's a brunch feature... according to the [brunch docs](https://github.com/brunch/brunch/blob/master/docs/config.md#conventions) for config option `conventions.assets`:

> key: anymatch set. Default value: /assets[\/]/. If test gives true, file won't be compiled and will be just moved to public directory instead.

You could change `conventions.assets` but it would be more conventional to move your `.static.jade` files elsewhere, such as `app/`.

**Comment by cappadona** [comment]
Thanks for setting me straight, @bmatcuk. Second time this has caught me off guard. Hopefully it will stick this time :)

**Comment by bmatcuk** [comment]
No problem! Let me know if you have any other issues =)
